# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

use_frameworks!

target 'TTTFramework-Example' do
  platform :ios, '11.0'
  pod 'LSRFramework', :path =>'../'

end
