# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

use_frameworks!

target 'TTTFramework-Example' do
  platform :ios, '8.0'
  
  pod 'TTTFramework', :path => '../', :isSource => true
  # pod 'TTTFramework'

end
